---
parser: babel-eslint
plugins:
- react
- react-hooks
extends:
- plugin:react/recommended
- standard
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: error
settings:
  react:
    version: 16.8.6
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
env:
  browser: true
  node: true
